### ISSUE TITLE
support (Un-)Subscribe events released in Spring 4.1

### ISSUE THREAD

**Issue by HadrienPierart** [zyro23/grails-spring-websocket#11]
Hi there,
I can't seem to find a way to get a notification on the server side when I ask stomp for an unsubscribe. Any suggestion ?

**Comment by zyro23** [comment]
2.0.0M1 has been released working together with grails-3.0.0.m2. that is based on spring-4.1.5 so all mentioned events will be available there. grails-2.4.x stays a dead end being locked onto spring-4.0.x.
