### ISSUE TITLE
support messaging security coming with Spring Security 4.0

### ISSUE THREAD

**Issue by Schlogen** [zyro23/grails-spring-websocket#12]
Hey there this more of a feature/documentation request.

I would really like to start using this, however I've been hard pressed to find examples on how to implement this securely. How can I broadcast messages to specific users? Is the current user available to me in the method where you return the data? Do the existing filters/annotations work to secure them by roles/authentication?

Thanks!

**Comment by zyro23** [comment]
a working 2.0.0M1 has been released which works with grails-3.0.0.m2. you can find some notes regarding spring-security in the readme. clsoing this one. if you are constrained to use the grails-2.4.x line, revisit the filtering approach with the custom interceptor above. that is essentially how it was implemented in spring-security-4 as well.

**Comment by moustaud** [comment]
great post ! 
I just have a question, if we want to send message to a groups of users, how can we pass it to parameter to the method  brokerMessagingTemplate.convertAndSendToUser ?

**Comment by zyro23** [comment]
you could obviously iterate over the users and send to each one of them. but its more common to do this by letting only those users subscribe to a specific topic (e.g. `myTopicForMySpecificUserGroup`) and just send to that.

**Comment by moustaud** [comment]
ok thanks a lot !

**Comment by moustaud** [comment]
Just another question, in this instraction : 
` brokerMessagingTemplate.convertAndSendToUser "dummy", "/queue/test", "only for dummy..."`
what is dummy ? a username ? a login ? and in what configuration file should I precise it (I mean 'dummy'. because I have in my user domain login, username etc.

**Comment by zyro23** [comment]
`dummy` is by default the username of the user that initiated the websocket connection. it is obtained from `request.getPrincipal()` and stored in the spring `WebSocketSession`. and if using spring-security, that normally matches an authenticated users' username.
