### ISSUE TITLE
Question: How to send message when connection to socket closed?

### ISSUE THREAD

**Issue by caseyscarborough** [zyro23/grails-spring-websocket#18]
I'm working on a chat application in Grails, and I was wondering if there was a way to send a notification to all users when another user disconnects (via navigation away from the page, reload, etc). Sending and receiving messages are working perfectly, using the example on the README, but this is the only thing I can't seem to figure out.

I've tried the following:

``` js
var socket = new SockJS("${createLink(uri: '/stomp')}");
var client = Stomp.over(socket);

socket.onclose = function() {
    client.send("/app/chatMessage", {}, JSON.stringify("User has disconnected"));
    client.disconnect();
}
```

I've also tried sending a message when the page unloads, but that doesn't seem to work either. Do you have any ideas?

Here is my controller and action:

``` groovy
class ChatController {

  @MessageMapping("/chatMessage")
  @SendTo("/topic/chatMessage")
  protected String message(String text) {
    return text
  }
}
```

Thanks in advance for the help.

**Comment by daptordarattler** [comment]
Sorry , this might be a noob question, but how do I inject the SessionEventListenerBean into my application context?

Thanks
