### ISSUE TITLE
Question - Grails 2.5

### ISSUE THREAD

**Issue by Schlogen** [zyro23/grails-spring-websocket#23]
With the release of 2.5 including Spring 4.1.x, can this plugin be used with it?

**Comment by zyro23** [comment]
hi, 1.3.0 released yesterday supporting grails-2.5.0 (spring-4.1.5). see 
* https://groups.google.com/d/msg/grails-dev-discuss/Rr0R3G07STA/UtSq08-Iy64J
* https://github.com/zyro23/grails-spring-websocket/issues/22
* https://github.com/zyro23/grails-spring-websocket/tree/1.3.x

zyro
