### ISSUE TITLE
Websocket connection gives Code 1006

### ISSUE THREAD

**Issue by anderskristian** [zyro23/grails-spring-websocket#24]
I have used the standard tomcat sample "Echo" to the sample URL 
/hello
When I connect I get error 1006

**Comment by zyro23** [comment]
could you please provide a sample app? or at least exact steps you tried the readme sample with (grails version etc.). thanks.

**Comment by zyro23** [comment]
is your ml post about the same problem? https://groups.google.com/d/topic/grails-dev-discuss/a10LdjbbSLY/discussion

if so, that does not look related to `grails-spring-websocket` in any way. please provide further info.

**Comment by anderskristian** [comment]
Yes it is related to that discussion.
I was not able to make grails-spring-websocket work. But I have not tried enough. 
I think we can close this issue.
