### ISSUE TITLE
How to have a service sending a message every five second

### ISSUE THREAD

**Issue by vatanbytyqi** [zyro23/grails-spring-websocket#27]
I'm trying to learn how spring and grails work with websocket and wonder how I can create a service that will send a message through the websocket every five second. I'm not wanting the client to send a message and the server to give a respons but a server that sends a message every five second to a client that has subscribed to an address. How would this be done with your plugin?

Thanks in advance!

**Comment by zyro23** [comment]
please refer to the readme (https://github.com/zyro23/grails-spring-websocket#service-brokermessagingtemplate-bean).

scheduling is out of scope wrt this plugin. you can ofc use spring(-core) scheduling, quartz, etc.

**Comment by vatanbytyqi** [comment]
I see, thank you very much!
