### ISSUE TITLE
Spring 4.2

### ISSUE THREAD

**Issue by aaloise** [zyro23/grails-spring-websocket#29]
Consider upgrading to Spring 4.2.3

**Comment by zyro23** [comment]
for grails milestone support, i.e. 3.1.x, right? will take care of it this week.

**Comment by aaloise** [comment]
Correct. Grails 3.0.x seems to be sticking with Spring 4.1.x

Grails 3.1.x is the one who is using Spring 4.2.x

**Comment by zyro23** [comment]
done with 2.3.0.M1 (grails-3.1.0.M3)
