### ISSUE TITLE
Exception when receiving messages from the client

### ISSUE THREAD

**Issue by AleCaste** [zyro23/grails-spring-websocket#3]
Hello,

I get an exception when receiving messages from the browser stomp client to the server.
My controller is exactly the same as the one you give as an example, but with the additional "message" parameter (as it is described here:  http://docs.spring.io/spring/docs/4.0.2.RELEASE/spring-framework-reference/html/websocket.html#websocket-stomp-handle ):

```
class ExampleController {

    def index() {}

    @MessageMapping("/hello")
    @SendTo("/topic/hello")
    protected String hello(String message) {
      println "RECEIVED MESSAGE:"+message
      return "hello from controller!"
    }

}
```

But when I run the app and send a message from the browser client, I get the following exception:

```
| Error 2014-05-06 10:17:32,921 [clientInboundChannel-3] ERROR springwebsocket.GrailsSimpAnnotationMethodMessageHandler  - Unhandled exception
Message: Could not read JSON: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: [B@2f1bfb; line: 1, column: 1]
   Line | Method
->> 886 | runTask in java.util.concurrent.ThreadPoolExecutor$Worker
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|   908 | run     in     ''
^   619 | run . . in java.lang.Thread

Caused by JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: [B@2f1bfb; line: 1, column: 1]
->> 164 | from    in com.fasterxml.jackson.databind.JsonMappingException
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|   691 | mappingException in com.fasterxml.jackson.databind.DeserializationContext
|    46 | deserialize in com.fasterxml.jackson.databind.deser.std.StringDeserializer
|    11 | deserialize in     ''
|   2993 | _readMapAndClose in com.fasterxml.jackson.databind.ObjectMapper
|   2199 | readValue in     ''
|   886 | runTask in java.util.concurrent.ThreadPoolExecutor$Worker
|   908 | run     in     ''
^   619 | run . . in java.lang.Thread
```

Is this related to this bug in Grails?
https://jira.grails.org/browse/GRAILS-11073

Is there a way to make it work?

Thanks!

**Comment by moustaud** [comment]
is it possible to send an array in client.send( ....) ??

**Comment by zyro23** [comment]
should be possible. depends ofc what your `@MessageMapping` method parameters look like. do you see any problem? if so, an example would be nice.

**Comment by moustaud** [comment]
Here is one part of my view code : 
`                 $("#sendButton").click(function() {
                    client.send("/app/brainstorm", {}, JSON.stringify($("#chatMessage").val()));
                });
            });
        </script>
    </head>
    <body>
        <section>
            <h2>Brainstorming</h2>                        
		    <input type="text" id="chatMessage" value="" style="width: 500px; height: 60px;" maxlength="255" /><br/>                          
	            <button id="sendButton">Send</button>
	            <div id="chatDiv"></div>           	         
        </section>
    </body>
</html>`


and in my controller, I want to get and the message and the name of the brainstorming like 'brainstorming 1. Here is what I have in my controller 
`@MessageMapping("/brainstorm")
	@SendTo("/topic/brainstorm")
	protected String brainstorm(String chatMsg) 
	{			
		def brains = /* here I want to get the brainstormin 1 */ 
             def builder = new JsonBuilder()
		builder 
		{
			message(chatMsg)
			timestamp(new Date().getTime())
		}
		builder.toString()
	}`

**Comment by zyro23** [comment]
dunno if i get your question right but probably you are just looking for one wrapper object:
```javascript
$("#sendButton").click(function() {
    var payload = {
        name: "someName",
        message: $("#chatMessage").val()
    };
    client.send("/app/brainstorm", {}, JSON.stringify(payload));
};
```
you will have to pull "someName" from wherever your "brainstormin 1" is defined.
that object can then be received in your controller message handler method not only as `String`, but also for example as `Map` or a custom object that would look like
```groovy
class ChatMessage {
    String name
    String message
}
```

**Comment by moustaud** [comment]
ok I try to do that. but if I get the object as a Map, how to access in each field ?

**Comment by moustaud** [comment]
What could be the cause for an error like 
`grails could not resolve view with name 'controllerName/action` ?

**Comment by zyro23** [comment]
map parameter:
```groovy
protected String hello(Map<String, Object> chatMessage) {
    println chatMessage.name
    println chatMessage.message
}
```

view resolution error:
that means your method handler is invoked as grails action. perhaps you are targeting it with a normal web request? make sure it is defined as `protected` or annotated with `@ControllerMethod` as described in the readme.

anyhow these are basically questions that do not really have sth. to do with the plugin but with language understanding and/or how spring-websocket works. please check the corresponding docs.

if you really find an issue (i.e. an error in the behavior or impl. of this plugin), please raise a new issue **including a reproducible sample app** instead of commenting here (as this is closed).

thx, zyro
