### ISSUE TITLE
Gradle 2.9

### ISSUE THREAD

**Issue by aaloise** [zyro23/grails-spring-websocket#30]
Consider upgrade Gradle to 2.9

**Comment by zyro23** [comment]
aem.. yup. however im curious: are you requesting this from a plugin user perspective or because you are working on/with a fork? should not make a difference when you are "just" using the plugin..

**Comment by aaloise** [comment]
I am a plugin user, but I noticed that since gradle 2.5 there is a lot of performance improvement effort. The goal here is to benefit this great plugin with those achievements.

**Comment by zyro23** [comment]
done with 2.2.0
