### ISSUE TITLE
Grails 3.0.10

### ISSUE THREAD

**Issue by aaloise** [zyro23/grails-spring-websocket#31]
Consider upgrading to Grails 3.0.10

**Comment by zyro23** [comment]
looks like that is not even released (https://github.com/grails/grails-core/releases)... do you perhaps mean 3.1.0.M2?

**Comment by aaloise** [comment]
You are rigth. It is not released yet (3.0.10).

Forgot to say "when it is released". Just trying to keep things up to date here, a lot of issues were fixed since 3.0.3

**Comment by zyro23** [comment]
done with 2.2.0
