### ISSUE TITLE
init socket SyntaxError

### ISSUE THREAD

**Issue by fit-booking** [zyro23/grails-spring-websocket#33]
Opening Web Socket...
VM20238:1 Uncaught SyntaxError: Unexpected token <
xo.onfinish @ sockjs.js?compile=false:1946
EventEmitter.emit @ sockjs.js?compile=false:148
that.xhr.onreadystatechange @ sockjs.js?compile=false:801

branch 1.3.x

after I add plugin to my grails app and add code from the readme file .
I got those error list here after I run-app

I need some help with it, I didn't change any code from the demo.

socket = new SockJS("${createLink( uri: '/stomp')}");

the problem may be whthin this line

**Comment by zyro23** [comment]
could the cause be that your request to `/stomp` hits a 301 redirect (for example because it is somehow secured or not allowed redirecting to a login form or similar)?

**Comment by zyro23** [comment]
have you made progress? only other issue i could imagine would be an assets encoding problem because `sock.js` contains unicode characters.

**Comment by fit-booking** [comment]
thank you very much , I got it done.
