### ISSUE TITLE
Conflict with URL Mapping

### ISSUE THREAD

**Issue by lsauwen** [zyro23/grails-spring-websocket#43]
Hello, 
when i use " ** " in url mappings (to accept slash and url like blog) the stocks.js show this error code in the console log: "VM7751:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0"

when i remove the " ** " all works fine.

the project avaliable in 
https://github.com/lsauwen/justpad

thanks

**Comment by zyro23** [comment]
i guess the url-mapping `**` catches the stomp endpoint (i.e. `/stomp/info`) as well. then that results in grails rendering a 404 page that starts with `<`. hence, your js error.

try excluding the stomp endpoint(s) from the urlmappings:
```groovy
class UrlMappings {
    static excludes = ["/stomp/**"]
    static mappings = {
        …
    }
}
```

**Comment by lsauwen** [comment]
when excludes stomp worked perfectly.

thank you

**Comment by lsauwen** [comment]
It was not a bug but a configuration issue in my project
