### ISSUE TITLE
How to detect a disconnection when the client turn off netwok.

### ISSUE THREAD

**Issue by zhouxutroy** [zyro23/grails-spring-websocket#45]
I found that when android client turn off network, the SessionDisconnectEvent was not triggered on the server side. 

How to detect a disconnection when the client turn off netwok ?

**Comment by zyro23** [comment]
i dug a bit into the docs around disconnections and heartbeats.
now i got the following understanding:
* if using sock.js support (which is default), there are two options
  * a sock.js fallback is used --> sock.js heartbeats are used
  * native websocket communication is used --> stomp heartbeats are *maybe* used

now, it also depends on the question if the simple broker impl is used or a real stomp message broker.
for the simple broker, server-side heartbeat-support has only been added with spring-4.2 and is disabled by default.

ref.:
* https://github.com/spring-projects/spring-framework/blob/v4.2.0.RELEASE/spring-messaging/src/main/java/org/springframework/messaging/simp/config/SimpleBrokerRegistration.java#L49
* https://github.com/spring-projects/spring-framework/blob/v4.2.0.RELEASE/spring-messaging/src/main/java/org/springframework/messaging/simp/config/SimpleBrokerRegistration.java#L63

so i did not yet test it but my suggestion would be to use create-web-socket-config and then use sth. like
```groovy
@Bean
ThreadPoolTaskScheduler webSocketHeartbeatTaskScheduler() {
    return new ThreadPoolTaskScheduler()
}

@Override
void configureMessageBroker(MessageBrokerRegistry messageBrokerRegistry) {
    messageBrokerRegistry
        .enableSimpleBroker("/queue", "/topic")
        .setTaskScheduler(webSocketHeartbeatTaskScheduler())
    messageBrokerRegistry.setApplicationDestinationPrefixes "/app"
}
```

feedback if this does the job would be great.

**Comment by adik993** [comment]
I've run into same problem and I can confirm that @zyro23 solution works, with just one small fix, you need to initialize TaskScheduler like that(otherwise spring yields error):
```java
@Bean
private TaskScheduler webSocketHeartbeatTaskScheduler() {
    ThreadPoolTaskScheduler scheduler = new ThreadPoolTaskScheduler();
    scheduler.afterPropertiesSet();
    return scheduler;
}
```

With default settings client `SessionDisconnectEvent` is tirggered after around 20s.

Thanks :+1:

**Comment by zyro23** [comment]
thanks for confirmation!
