### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 404

### ISSUE THREAD

**Issue by asuraphel** [zyro23/grails-spring-websocket#47]
I have setup the `1.3.1` version of the plugin as per the docs but I get the following error in Chrome: 

`sockjs.js?compile=false:1213 WebSocket connection to 'ws://localhost:8098/hms/stomp/428/nb0d01u8/websocket' failed: Error during WebSocket handshake: Unexpected response code: 404`

**Comment by zyro23** [comment]
please attach a sample app reproducing the issue.
clearly, it works by following the docs for other people.
maybe the 404 just means that there is no websocket support and after that sock.js uses a fallback transport?

**Comment by asuraphel** [comment]
@zyro23 Is tomcat 7.0.52+ required? I tried upgrading but [I am having issues with it](https://github.com/grails-plugins/grails-tomcat-plugin/issues/23).

**Comment by asuraphel** [comment]
@zyro23 just solved my issue. I see no errors now.. If I can.. I have one more question though. `client.send` doesn't seem to do anything. I used chrome dev tools to inspect network traffic. Nothing seems to show up. What could I be missing? 

Here is my code: 

```
    $(function() {
        var socket = new SockJS("/appName/stomp");
        var client = Stomp.over(socket);


        $(".call-nurse-button").click(function() {
            client.send("/app/messageDestination", {}, 'Message');
        });
    });
```

Log on console: 

> >>> SEND
> destination:/app/messageDestination
> content-length:26
> 
> Message

Thanks!

**Comment by asuraphel** [comment]
Solved. Thanks for your responsiveness.

**Comment by asuraphel** [comment]
Solved. Thanks for your responsiveness.
