### ISSUE TITLE
Does it work with grails 3.3.3 ?

### ISSUE THREAD

**Issue by Nichlas-Lendal-Nine** [zyro23/grails-spring-websocket#60]
Does it work with grails 3.3.3 ? 
I got stuck where my client (frontend) was getting a 404 status from the backend on /stomp/info?some=parameter.

I ended op actually wiring up the configuration and the plugin my self - and it startet working?

Dont know if i did something wrong or if it is not supported by grails 3.3.3 atm?

**Comment by erichelgeson** [comment]
I'm using it in Grails 3.3.3 without issues - maybe post a sample project that shows the issue?

**Comment by Nichlas-Lendal-Nine** [comment]
**Issue**
Failed to load resource: the server responded with a status of 404 () : 8080/stomp/info

Note: I was using Chrome - and the abose is the console output from developer tools.

**Steps to reproduce**
1. grails create-app NAME --profile=web
2. add dependency "compile "org.grails.plugins:grails-spring-websocket:2.4.0"
3. Add the index.gsp from your README.md
4. Add the ExampleController from your README.md
5. gradlew bootRun
6. Navigate to http://localhost:8080 

**Sample project**
https://github.com/Nichlas-Lendal-Nine/GRAILS-SPRING-WEBSOCKET-ISSUE

I somehow thinks its something about the configuration not beeing wired.

**Comment by zyro23** [comment]
thank you for the sample app. could reproduce and fix the issue (see 0bec520c7a).

just pushed a 2.4.1 that works as expected.

cause was that it seems while the 2.4.0.M1 release was properly built, for the 2.4.0 build the boot gradle plugin bootRepackage task kicked in, restructuring/blowing up the jar. i do not know why/how that happened as between 2.4.0.M1 and 2.4.0 i only fiddled with the readme and the release process was/is the same. however, for now, explicitly disabling the bootRepackage task helped. i ran your sample app with 2.4.1 and it looks/works fine.

ill keep this one open for a bit - would be kind if you would close it after verifying the fix.

sorry for the inconvenience..

**Comment by Nichlas-Lendal-Nine** [comment]
Just verified that version 2.4.1 works as expected. Thank you.

**Comment by wiggitamoo** [comment]
When running Nichlas' steps to reproduce on 2.4.1, I see the following error.

```
Uncaught ReferenceError: webstomp is not defined
```

**Comment by zyro23** [comment]
please refer to the readme on the `2.4.x` branch. webstomp.js support was introduced with `2.5.0`.

**Comment by wiggitamoo** [comment]
Thanks @zyro23, that was my problem.
