### ISSUE TITLE
How to use with an external broker like ActiveMQ

### ISSUE THREAD

**Issue by ganeshkantu** [zyro23/grails-spring-websocket#62]
I have been successfully using this plugin with the embedded broker. Now want to migrate to a more distributed structure - very confused as to how I would setup using an ActiveMQ broker. Any pointers?

**Comment by zyro23** [comment]
readme: https://github.com/zyro23/grails-spring-websocket#full-featured-broker

spring docs:
- https://docs.spring.io/spring/docs/4.3.14.RELEASE/spring-framework-reference/html/websocket.html#websocket-stomp-handle-broker-relay
- https://docs.spring.io/spring/docs/4.3.14.RELEASE/spring-framework-reference/html/websocket.html#websocket-stomp-handle-broker-relay-configure

activemq stomp transport: http://activemq.apache.org/stomp.html

good websocket sample app: https://github.com/rstoyanchev/spring-websocket-portfolio

> You may also need to configure additional STOMP broker relay properties such as `relayHost`, `relayPort`, `systemLogin`, `systemPassword`, depending on your message broker. The default settings should work for RabbitMQ and ActiveMQ.
