### ISSUE TITLE
Closing session event is being logged in at ERROR level

### ISSUE THREAD

**Issue by ChiranjibKarn** [zyro23/grails-spring-websocket#66]
We are using this plugin in Grails 3.3.8 REST application. In log I can see many ERROR level log like below  

> ERROR o.s.w.s.m.SubProtocolWebSocketHandler - No messages received after <some_num> ms. Closing **EventSourceStreamingSockJsSession**[id=<some_session_id>]

> ERROR o.s.w.s.m.SubProtocolWebSocketHandler - No messages received after <some_num> ms. Closing **XhrStreamingSockJsSession**[id=<some_session_id>]

> ERROR o.s.w.s.m.SubProtocolWebSocketHandler - No messages received after <some_num> ms. Closing **WebSocketServerSockJsSession**[id=<some_session_id>]

Should not these logs be logged at INFO level?

**Comment by zyro23** [comment]
which spring-websocket version is being used? grails-3.3.8 with grails-spring-webocket should pull in spring-websocket-4.3.18 and that should not log excessive errors
* ref. https://jira.spring.io/browse/SPR-16409
* and https://github.com/spring-projects/spring-framework/blob/v4.3.18.RELEASE/spring-websocket/src/main/java/org/springframework/web/socket/messaging/SubProtocolWebSocketHandler.java

anyway, that logging is part of spring-websocket and not this plugin. if you really find an issue, it may make sense to open a corresponding spring issue.

hth

**Comment by ChiranjibKarn** [comment]
Am using grails-spring-websocket:2.4.1 and yes it is pulling spring-websocket-4.3.18.RELEASE, but still getting this issue.  
Anyway, thank you for pointing that JIRA ticket, I will open an issue in spring-websocket issue tracker.

**Comment by zyro23** [comment]
just in case you did not spot the related change yet:

https://github.com/spring-projects/spring-framework/commit/09cb7f4c310b66cdf46bdc4934eee7f0536dbee2#diff-e06394d1d8cb023d3a8ee380f468de8fL468

and that is definitively in 4.3.18:

https://github.com/spring-projects/spring-framework/blame/v4.3.18.RELEASE/spring-websocket/src/main/java/org/springframework/web/socket/messaging/SubProtocolWebSocketHandler.java#L471-L474
